apiVersion: apps/v1 
kind: Deployment 
metadata: 
    name: frontend
    labels: 
        app: frontend
        tier: frontend 
spec: 
    replicas: 1
    selector: 
        matchLabels:   ## Must be checked 
            app: frontend
           
    template:
        metadata: 
            name: frontend 
            labels: 
                app: frontend 
        spec: 
            containers: 
            -   name: frontend
                image: gcr.io/google-samples/microservices-demo/frontend:v0.4.2
                ports: 
                -   containerPort: 8080
                env: 
                - name: PORT
                  value: "8080"
                - name: PRODUCT_CATALOG_SERVICE_ADDR
                  value: "productcatalogservice:3550"
                - name: CURRENCY_SERVICE_ADDR
                  value: "currencyservice:7000"
                - name: CART_SERVICE_ADDR
                  value: "cartservice:7070"
                - name: RECOMMENDATION_SERVICE_ADDR
                  value: "recommendationservice:8080"
                - name: SHIPPING_SERVICE_ADDR
                  value: "shippingservice:50051"
                - name: CHECKOUT_SERVICE_ADDR
                  value: "checkoutservice:5050"
                - name: AD_SERVICE_ADDR
                  value: "adservice:9555"
          
              
--- 
apiVersion: v1 
kind: Service
metadata: 
  name: frontend-svc 
spec: 
  selector: 
    app: frontend
  type: NodePort
  ports: 
  - protocol: TCP 
    port: 8080 
    targetPort: 8080 
    nodePort: 31000
    
