---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
  labels:
    app: shopfront
  namespace: shopfront
spec:
  type: NodePort
  selector:
    app: shopfront
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
    nodePort: 31100
    name: http

